# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class NotionMdGen < Formula
    desc "notion-md-gen allows you to use Notion as a CMS for pages built with any static site generators"
    homepage "https://github.com/saltbo/notion-md-gen"
    version "v1.1.1-next"
  
    on_macos do
      if Hardware::CPU.arm?
        url "https://github.com/saltbo/notion-md-gen/releases/download/v1.1.1/notion-md-gen-macos-arm64.tar.gz"
        sha256 "2137218ee6372cfaacf303f6382e84e806ca04888c7293998863d1324eae02bd"
  
        def install
          bin.install "notion-md-gen"
        end
      end
      if Hardware::CPU.intel?
        url "https://github.com/saltbo/notion-md-gen/releases/download/v1.1.1/notion-md-gen-macos-amd64.tar.gz"
        sha256 "1a9f3cd743682384e682cf7a3b121416f56fef25e866df428d9dfd258062b1f7"
  
        def install
          bin.install "notion-md-gen"
        end
      end
    end
  
    on_linux do
      if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
        url "https://github.com/saltbo/notion-md-gen/releases/download/v1.1.1/notion-md-gen-linux-arm64.tar.gz"
        sha256 "9e25d6bafcc9aa9d9e1fbfada6058c6dba2f05ee22b4ad859cae42a865ecaaf6"
  
        def install
          bin.install "notion-md-gen"
        end
      end
      if Hardware::CPU.intel?
        url "https://github.com/saltbo/notion-md-gen/releases/download/v1.1.1/notion-md-gen-linux-amd64.tar.gz"
        sha256 "0e7a4919b19728b06295e57f5d6e65a448e1fde60f389e8f4b8116d7efa98d3f"
  
        def install
          bin.install "notion-md-gen"
        end
      end
    end
  
    test do
      system "#{bin}/notion-md-gen", "--version"
    end
  end
  