# This file was generated by GoReleaser. DO NOT EDIT.
class Uptoc < Formula
  desc "Convenient static file deployment tool that supports multiple platforms"
  homepage "https://github.com/saltbo/uptoc"
  version "1.4.3"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/saltbo/uptoc/releases/download/v1.4.3/uptoc-macos-amd64.tar.gz"
    sha256 "78768aa26999c20fc55c929c458613d6d686b3ce87bfa61950f6d76d768b721c"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/saltbo/uptoc/releases/download/v1.4.3/uptoc-linux-amd64.tar.gz"
      sha256 "959acea0412cf4990900d1490b67c4e35b93230a3fa06e8d5a85d30b08ca049d"
    end
  end

  def install
    bin.install "uptoc"
  end

  test do
    system "#{bin}/uptoc", "--version"
  end
end
