# This file was generated by GoReleaser. DO NOT EDIT.
class Uptoc < Formula
  desc "Convenient static file deployment tool that supports multiple platforms"
  homepage "https://github.com/saltbo/uptoc"
  version "1.4.3"

  if OS.mac?
    url "https://github.com/saltbo/uptoc/releases/download/v1.4.3/uptoc-macos-amd64.tar.gz"
    sha256 "21dab0f626307bba09caf28f20105a0d962de8b48d873fc79c62e804caa4c87a"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/saltbo/uptoc/releases/download/v1.4.3/uptoc-linux-amd64.tar.gz"
      sha256 "fa24759943d3b45721f9a5031bb33613b7ac880ba0f08d9aeef914299baf0be9"
    end
  end

  def install
    bin.install "uptoc"
  end

  test do
    system "#{bin}/uptoc", "--version"
  end
end
