# This file was generated by GoReleaser. DO NOT EDIT.
class Uptoc < Formula
  desc "A static file deployment tool that supports multiple platforms"
  homepage "https://github.com/saltbo/uptoc"
  version "1.4.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/saltbo/uptoc/releases/download/v1.4.0/uptoc-macos-amd64.tar.gz"
    sha256 "3589f351393bd76ea05b37929fb9cb627bd73a903bd866646e5829575458de3b"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/saltbo/uptoc/releases/download/v1.4.0/uptoc-linux-amd64.tar.gz"
      sha256 "7cf98b0636c6025667dd56dc6814403146e1a6f175674ce00ab735a7cae467bb"
    end
  end

  def install
    bin.install "uptoc"
  end

  test do
    system "#{bin}/uptoc --version"
  end
end
